name: Check
on: [pull_request]
permissions:
  contents: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: extractions/setup-just@v1
      - run: just install
      - run: |
          git fetch origin
          pre-commit run --from-ref origin/${{ github.event.pull_request.base.ref }} --to-ref ${{ github.event.pull_request.head.sha }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
         # --8<-- [start:python-versions]
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        # --8<-- [end:python-versions]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: extractions/setup-just@v1
      - run: just install
      - run: just test-with-coverage
      - uses: codecov/codecov-action@v4
