name: Check
on: [pull_request]
permissions:
  contents: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: extractions/setup-just@v2
      - run: just install
      - run: just lint
      - run: just format-check
      - run: just security

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
         # --8<-- [start:python-versions]
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        # --8<-- [end:python-versions]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - uses: extractions/setup-just@v2
      - name: Set Python version
        run: echo "UV_PYTHON=${{ matrix.python-version }}" >> $GITHUB_ENV
      - run: just install
      - run: just test-with-coverage
      - uses: codecov/codecov-action@v4
