name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9"]
        os:
          # --8<-- [start:oses]
          - "ubuntu-18.04"
          - "windows-latest"
          - "macos-latest"
          # --8<-- [end:oses]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: extractions/setup-just@v1
      - run: just install
      - name: Build report and package
        if: matrix.os == 'ubuntu-18.04'
        run: |
          just build
          just package-report
      - uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.TWINE_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-18.04'
        with:
          path: airflow_report.pyz
      - run: just package-pyinstaller
      - uses: actions/upload-artifact@v3
        with:
          path: |
            telescope-*

  release:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/download-artifact@v3
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        generate_release_notes: true
        files: |
          artifact/airflow_report.pyz
          artifact/telescope-*
